<?php
try {
    $sql = <<<SQL
CREATE TABLE IF NOT EXISTS `intra_edivi` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `patname` varchar(255) DEFAULT NULL,
  `patgebdat` date DEFAULT NULL,
  `patsex` tinyint(1) DEFAULT NULL,
  `edatum` date DEFAULT NULL,
  `ezeit` varchar(255) DEFAULT NULL,
  `enr` varchar(255) NOT NULL,
  `eort` varchar(255) DEFAULT NULL,
  `sendezeit` datetime DEFAULT current_timestamp(),
  `awfrei_1` tinyint(1) DEFAULT NULL,
  `awfrei_2` tinyint(1) DEFAULT NULL,
  `awfrei_3` tinyint(1) DEFAULT NULL,
  `awsicherung_1` tinyint(1) DEFAULT NULL,
  `awsicherung_2` tinyint(1) DEFAULT NULL,
  `awsicherung_neu` tinyint(1) DEFAULT NULL,
  `zyanose_1` tinyint(1) DEFAULT NULL,
  `zyanose_2` tinyint(1) DEFAULT NULL,
  `o2gabe` tinyint(15) DEFAULT 0,
  `b_symptome` tinyint(4) DEFAULT NULL,
  `b_auskult` tinyint(3) DEFAULT NULL,
  `b_beatmung` tinyint(3) DEFAULT NULL,
  `spo2` varchar(255) DEFAULT NULL,
  `atemfreq` varchar(255) DEFAULT NULL,
  `etco2` varchar(255) DEFAULT NULL,
  `c_kreislauf` tinyint(2) DEFAULT NULL,
  `rrsys` varchar(255) DEFAULT NULL,
  `rrdias` varchar(255) DEFAULT NULL,
  `herzfreq` varchar(255) DEFAULT NULL,
  `c_ekg` tinyint(9) DEFAULT NULL,
  `c_zugang_art_1` tinyint(9) DEFAULT NULL,
  `c_zugang_gr_1` tinyint(9) DEFAULT NULL,
  `c_zugang_ort_1` varchar(255) DEFAULT NULL,
  `c_zugang_art_2` tinyint(9) DEFAULT NULL,
  `c_zugang_gr_2` tinyint(9) DEFAULT NULL,
  `c_zugang_ort_2` varchar(255) DEFAULT NULL,
  `c_zugang_art_3` tinyint(9) DEFAULT NULL,
  `c_zugang_gr_3` tinyint(9) DEFAULT NULL,
  `c_zugang_ort_3` varchar(255) DEFAULT NULL,
  `d_bewusstsein` tinyint(3) DEFAULT NULL,
  `d_pupillenw_1` tinyint(3) DEFAULT NULL,
  `d_pupillenw_2` tinyint(3) DEFAULT NULL,
  `d_lichtreakt_1` tinyint(2) DEFAULT NULL,
  `d_lichtreakt_2` tinyint(2) DEFAULT NULL,
  `d_gcs_1` tinyint(3) DEFAULT NULL,
  `d_gcs_2` tinyint(4) DEFAULT NULL,
  `d_gcs_3` tinyint(5) DEFAULT NULL,
  `d_ex_1` tinyint(2) DEFAULT NULL,
  `bz` varchar(255) DEFAULT NULL,
  `temp` varchar(255) DEFAULT NULL,
  `v_muster_k` tinyint(3) DEFAULT NULL,
  `v_muster_k1` tinyint(2) DEFAULT NULL,
  `v_muster_w` tinyint(3) DEFAULT NULL,
  `v_muster_w1` tinyint(2) DEFAULT NULL,
  `v_muster_t` tinyint(3) DEFAULT NULL,
  `v_muster_t1` tinyint(2) DEFAULT NULL,
  `v_muster_a` tinyint(3) DEFAULT NULL,
  `v_muster_a1` tinyint(2) DEFAULT NULL,
  `v_muster_al` tinyint(3) DEFAULT NULL,
  `v_muster_al1` tinyint(2) DEFAULT NULL,
  `v_muster_ar` tinyint(3) DEFAULT NULL,
  `v_muster_ar1` tinyint(2) DEFAULT NULL,
  `v_muster_bl` tinyint(3) DEFAULT NULL,
  `v_muster_bl1` tinyint(2) DEFAULT NULL,
  `v_muster_br` tinyint(3) DEFAULT NULL,
  `v_muster_br1` tinyint(2) DEFAULT NULL,
  `sz_nrs` tinyint(2) DEFAULT NULL,
  `sz_toleranz_1` tinyint(2) DEFAULT NULL,
  `sz_toleranz_2` tinyint(2) DEFAULT NULL,
  `medis` longtext DEFAULT NULL,
  `diagnose` text DEFAULT NULL,
  `anmerkungen` text DEFAULT NULL,
  `pfname` varchar(255) DEFAULT NULL,
  `prot_by` tinyint(1) DEFAULT NULL,
  `fzg_transp` varchar(255) DEFAULT NULL,
  `fzg_transp_perso` varchar(255) DEFAULT NULL,
  `fzg_transp_perso_2` varchar(255) DEFAULT NULL,
  `fzg_na` varchar(255) DEFAULT NULL,
  `fzg_na_perso` varchar(255) DEFAULT NULL,
  `fzg_na_perso_2` varchar(255) DEFAULT NULL,
  `fzg_sonst` varchar(255) DEFAULT NULL,
  `naname` varchar(255) DEFAULT NULL,
  `transportziel` varchar(255) DEFAULT NULL,
  `protokoll_status` tinyint(3) DEFAULT 0,
  `bearbeiter` varchar(255) DEFAULT NULL,
  `qmkommentar` text DEFAULT NULL,
  `freigegeben` tinyint(1) DEFAULT 0,
  `freigeber_name` varchar(255) DEFAULT NULL,
  `last_edit` timestamp NULL DEFAULT NULL,
  `hidden` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2498 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
SQL;

    $pdo->exec($sql);
} catch (PDOException $e) {
    $message = $e->getMessage();
    echo $message;
}
